package com.keyloop.docviewer.persistence;

import com.keyloop.docviewer.domain.Document;
import com.keyloop.docviewer.domain.SourceSystem;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "document_snapshot")
class DocumentSnapshotEntity {

    // Generated by Hibernate (not assigned by us) so save() persists instead of merging,
    // which would otherwise cost one SELECT per row.
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, length = 17)
    private String vin;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private SourceSystem source;

    @Column(name = "external_id", nullable = false)
    private String externalId;

    @Column(name = "document_type")
    private String documentType;

    private String title;

    private String reference;

    @Column(name = "issued_at")
    private Instant issuedAt;

    private String url;

    @Column(name = "fetched_at", nullable = false)
    private Instant fetchedAt;

    protected DocumentSnapshotEntity() {
    }

    static DocumentSnapshotEntity of(String vin, Document document, Instant fetchedAt) {
        DocumentSnapshotEntity entity = new DocumentSnapshotEntity();
        entity.vin = vin;
        entity.source = document.source();
        entity.externalId = document.externalId();
        entity.documentType = document.type();
        entity.title = document.title();
        entity.reference = document.reference();
        entity.issuedAt = document.issuedAt();
        entity.url = document.url();
        entity.fetchedAt = fetchedAt;
        return entity;
    }

    Document toDocument() {
        return new Document(externalId, source, documentType, title, reference, issuedAt, url);
    }
}
